name: Node Version
on:
  push:
    branches: [ 1107-test ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16.x
        uses: actions/setup-node@v5
        with:
          node-version: '16.x'
